# Generated by Django 6.0.6 on 2026-06-24 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('solicitud', 'Solicitud'), ('aceptada', 'Solicitud aceptada'), ('rechazada', 'Solicitud rechazada'), ('cancelada', 'Solicitud cancelada'), ('completada', 'Solicitud completada'), ('mensaje', 'Nuevo mensaje'), ('encuentro', 'Punto de encuentro')], max_length=20)),
                ('mensaje', models.CharField(max_length=255)),
                ('enlace', models.CharField(blank=True, max_length=255)),
                ('leido', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
