services:
  - type: web
    name: librolibre
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput --no-post-process
    preDeployCommand: python manage.py migrate && python manage.py crear_superuser
    startCommand: gunicorn librolibre.wsgi:application --workers 2 --timeout 120
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: libro-libre1.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: librolibre-db
          property: connectionString
      - key: SUPABASE_ACCESS_KEY
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: SUPABASE_BUCKET
        sync: false
      - key: SUPABASE_ENDPOINT_URL
        sync: false

databases:
  - name: librolibre-db
    databaseName: librolibre
    plan: free
