# Generated by Django 6.0.6 on 2026-06-24 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoEncuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('fecha_entrega', models.DateField()),
                ('hora_entrega', models.TimeField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='punto_encuentro', to='solicitudes.solicitud')),
            ],
        ),
    ]
